#!/bin/bash

set -euo pipefail

# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Seweryn Sitarski
# Author: Seweryn Sitarski
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
# See the LICENSE file for details.

usage() {
  cat <<EOF
Usage: $0 OUTDIR

Build the netboot container image and export:
- vmlinuz-<kernel-version>
- initrd.img-<kernel-version>-<git-version>

Symlinks named vmlinuz and initrd.img are also created in OUTDIR.

Environment overrides:
- CONTAINER_CLI   Container runtime command to use (default: docker)
- IMAGE_NAME      Image name to build (default: bocm)
- BUILD_NETWORK   Network mode passed to build (default: host)
EOF
}

if [ "$#" -eq 0 ]; then
  usage
  exit 1
fi

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
esac

if [ "$#" -ne 1 ]; then
  usage
  exit 1
fi

OUTDIR=$1
CONTAINER_CLI=${CONTAINER_CLI:-docker}
IMAGE_NAME=${IMAGE_NAME:-bocm}
BUILD_NETWORK=${BUILD_NETWORK:-host}
CONTAINER=""
DIR=$(pwd)

cleanup() {
  rm -f "${DIR}/etc/bocm/VERSION"
  if [ -n "${CONTAINER}" ]; then
    "${CONTAINER_CLI}" stop -t 0 "${CONTAINER}" >/dev/null 2>&1 || true
  fi
}

trap cleanup EXIT

RUNOPT=(
  -v "${DIR}/etc/bocm:/etc/bocm"
  -v "${DIR}/etc/initramfs-tools:/etc/initramfs-tools"
)

VER=$(git describe --long 2>&1)
if echo "${VER}" | grep -q fatal; then
  VER=$(git describe --all --long)
fi
echo "${VER}" > "${DIR}/etc/bocm/VERSION"

mkdir -p "${OUTDIR}"

"${CONTAINER_CLI}" build --network="${BUILD_NETWORK}" -t "${IMAGE_NAME}" ./
CONTAINER=$("${CONTAINER_CLI}" run -d --rm "${RUNOPT[@]}" "${IMAGE_NAME}" /bin/sleep 1000)
KERNELV=$("${CONTAINER_CLI}" exec "${CONTAINER}" bash -lc 'basename "$(readlink -f /vmlinuz)" | sed "s/^vmlinuz-//"')
"${CONTAINER_CLI}" exec "${CONTAINER}" update-initramfs -c -k "${KERNELV}"
KERNEL=$("${CONTAINER_CLI}" exec "${CONTAINER}" readlink -f /vmlinuz)
INITRD=$("${CONTAINER_CLI}" exec "${CONTAINER}" readlink -f /initrd.img)
"${CONTAINER_CLI}" cp "${CONTAINER}:${KERNEL}" "${OUTDIR}/vmlinuz-${KERNELV}"
ln -sf "./vmlinuz-${KERNELV}" "${OUTDIR}/vmlinuz"
chmod go+r "${OUTDIR}/vmlinuz"*
"${CONTAINER_CLI}" cp "${CONTAINER}:${INITRD}" "${OUTDIR}/initrd.img-${KERNELV}-${VER}"
ln -sf "./initrd.img-${KERNELV}-${VER}" "${OUTDIR}/initrd.img"
