#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Seweryn Sitarski
# Author: Seweryn Sitarski
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
# See the LICENSE file for details.


if [ "$#" == 0 ]; then
  printf "Poprawne wywołanie: $0 sciezka_katalogu_w_ktorym_ma_byc zapisany initrd.img i vmlinuz\n"
  exit ${PARAMERROR}
fi

OUTDIR=$1
IMAGE_NAME=bocm
#CONTAINER=bocm
DIR=$(pwd)
RUNOPT="-v ${DIR}/etc/bocm:/etc/bocm -v ${DIR}/etc/initramfs-tools:/etc/initramfs-tools"

VER=$(git describe --long 2>&1)
if echo ${VER}|grep -q fatal; then
  VER=$(git describe --all --long)
fi
echo ${VER} > etc/bocm/VERSION

docker build -t ${IMAGE_NAME} ./ && \
CONTAINER=$(docker run -d --rm ${RUNOPT} ${IMAGE_NAME} /bin/sleep 1000) && \
#KERNELV=$(docker exec ${CONTAINER} ls -l /boot/vmlinuz|awk '{ print $11 }') && \
#KERNELV=${KERNELV#vmlinuz-} && \
KERNELV=$(docker exec ${CONTAINER} bash -lc 'basename "$(readlink -f /vmlinuz)" | sed "s/^vmlinuz-//"') && \
docker exec ${CONTAINER} update-initramfs -c -k ${KERNELV} && \ 
KERNEL=$(docker exec ${CONTAINER} readlink -f /vmlinuz) && \
INITRD=$(docker exec ${CONTAINER} readlink -f /initrd.img) && \
docker cp ${CONTAINER}:${KERNEL} ${OUTDIR}/vmlinuz-${KERNELV} && \
ln -sf ./vmlinuz-${KERNELV} ${OUTDIR}/vmlinuz && \
chmod go+r ${OUTDIR}/vmlinuz* && \
docker cp ${CONTAINER}:${INITRD} ${OUTDIR}/initrd.img-${KERNELV}-${VER} && \
ln -sf ./initrd.img-${KERNELV}-${VER} ${OUTDIR}/initrd.img && \
docker stop -t 0 ${CONTAINER}

rm -f etc/bocm/VERSION
