#!/bin/bash
source global

if [ "$#" == 0 ]; then
  printf "Poprawne wywołanie: $0 nazwa_katalogu_zawierajacego_obraz_kontenerai\n"
  exit ${PARAMERROR}
fi

IMGSRC=$1

if ! [ -d ${IMGSRC} ]; then
  printf "Katalog z obrazem kontenera nie istnieje!\n"
  exit ${DIRERROR}
fi

read -p "Czy budowac obraz z katalogu ${IMGSRC}? (t/n): " ANS
if [ ${ANS} != 't' ] && [ ${ANS} != 'T' ]; then
  exit 0
fi

printf "Budowanie kontenera..."
IMG=$(${IMGSRC}/${BUILDSCR})
if [ ${IMG} = 'Error' ]; then
  printf "Budowanie kontenera zakonczone bledem!\n"
  exit ${BUILDERROR}
fi
printf " ${IMG} OK\n"

TEMPLATE=${IMG%:*}
OUTDIR=$(dirname ${IMGSRC})

CONTAINER=$(docker run -d --rm ${RUNOPT} ${IMG} /bin/sleep 1000) \
&& for F in ${IMGSRC}/bocm/*; do docker cp $(readlink -f ${F}) ${CONTAINER}:/etc/bocm/; done \
&& KERNEL=$(docker exec ${CONTAINER} readlink -f /vmlinuz) \
&& INITRD=$(docker exec ${CONTAINER} readlink -f /initrd.img) \
&& printf "Aktualizuje initramfs... "; docker exec ${CONTAINER} update-initramfs -c -k all > /dev/null; printf "OK\n" \
&& docker cp ${CONTAINER}:${KERNEL} ${OUTDIR}/vmlinuz \
&& chmod go+r ${OUTDIR}/vmlinuz \
&& docker cp ${CONTAINER}:${INITRD} ${OUTDIR}/initrd.img \
&& docker stop -t 0 ${CONTAINER} > /dev/null \
&& CONTAINER=$(docker run -d ${IMG} /bin/sleep 1000) \
&& docker stop -t 0 ${CONTAINER} > /dev/null \
&& printf "Eksportuje kontener do archiwum tgz... "; docker export ${CONTAINER}|pigz > ${OUTDIR}/${TEMPLATE}.tgz; printf "OK\n" \
&& docker rm ${CONTAINER} > /dev/null


