#!/bin/sh
#set -x
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line


# from /usr/share/initramfs-tools/scripts/nfs
manual_add_modules nfs
# For DHCP
manual_add_modules af_packet
copy_exec /sbin/dhclient
copy_exec ${BOCMDIR}/dhclient-script /sbin

copy_exec /bin/ln 

copy_exec /bin/chown

copy_exec /sbin/sgdisk /sbin
copy_exec /sbin/partprobe /sbin
copy_exec /bin/lsblk /bin
copy_exec /sbin/wipefs /sbin

copy_exec /sbin/mkfs.xfs /sbin
copy_exec /sbin/fsck.xfs /sbin
copy_exec /sbin/xfs_repair /sbin
copy_exec /usr/sbin/xfs_db /sbin
copy_exec /sbin/mkfs.vfat /sbin
copy_exec /sbin/mkswap /sbin
copy_exec /usr/bin/rsync /bin
# Dodane recznie, poniewaz standardowy skrypt /usr/share/initramfs-tools/hooks/fsck
# podczas wykrywania czy sa potrzebne narzedzia weryfikuje typ systemu plikow ROOT
# poniewaz budujemy initramfs w srodowisku kontenerowym, to nie ma prawidlowego ROOT fs-a
# narzedzia sa wykorzystywane standardowo do sprawdzenia ROOT fs-a podczas bootowania
copy_exec /sbin/fsck
copy_exec /sbin/logsave

copy_exec /sbin/vconfig

# Dodane po to by dzialal dns
for _LIBRARY in /lib/x86_64-linux-gnu/libnss_dns*
do
        if [ -e "${_LIBRARY}" ]
        then
                copy_exec ${_LIBRARY} /lib
        fi
done

copy_exec /bin/tar /bin
copy_exec /usr/bin/zstd /bin
#copy_exec /usr/bin/wget /usr/bin/wget
copy_exec /bin/bash /bin/bash
copy_exec /usr/bin/pv /bin/pv
copy_exec /rclone/rclone /bin/rclone
copy_exec /usr/bin/ping /bin/ping

copy_file RCLONE_CONF /etc/bocm/rclone.conf 

# Kopiowanie klucza dostepowego do boipxe
copy_file BOCM_key /etc/bocm/boipxe_rsa
# Zmiana uprawnien, git nie przenosi uprawnien klucz prywatny musi miec konkretne
chmod 600 ${DESTDIR}/etc/bocm/boipxe_rsa
copy_file BOCM_key_pub /etc/bocm/boipxe_rsa.pub

# Na potrzeby formatowania dysku
copy_file BOCM_default /etc/bocm/default
copy_file BOCM_functions /etc/bocm/functions.sh
copy_file BOCM_fstab /etc/bocm/fstab
copy_file BOCM_partitions.yml /etc/bocm/partitions.yml
copy_file BOCM_bash_yaml /etc/bocm/bash-yaml/script/yaml.sh
copy_file BOCM_VERSION /etc/bocm/VERSION

# Na potrzeby klienta ssh
copy_file SSH_PASSWD /etc/passwd /etc/passwd

# Narzedzie do listowania dyskow
copy_file DISK_INFO /usr/local/sbin/disk_info /bin/disk_info

# Dodanie shella fish
#copy_exec /usr/bin/fish /usr/bin/fish
#mkdir -p ${DESTDIR}/usr/share/fish/
#cp -ar /usr/share/fish/* ${DESTDIR}/usr/share/fish/

exit 0
