#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Kopiuj niestandardowy plik konfiguracyjny klienta DHCP do obrazu initramfs
copy_file DHCP_CONF /etc/initramfs-tools/etc/custom-dhclient.conf /etc/custom-dhclient.conf